### ISSUE TITLE
Could not find or load main class kotlinx.benchmark.jvm.JvmBenchmarkRunnerKt

### ISSUE THREAD

**Issue by deepak-nulu** [Kotlin/kotlinx-benchmark#46]
I am trying to use `kotlinx-benchmark` in an open source project. I followed all the instructions but I am getting the following error when I try to run the benchmarks from the Gradle panel in IntelliJ IDEA:

```
Could not find or load main class kotlinx.benchmark.jvm.JvmBenchmarkRunnerKt
```

My changes to `build.gradle.kts` can be seen in the following pull-request:

https://github.com/tree-ware/tree-ware-kotlin-core/pull/13/files

I am interested only in JVM benchmarks. I tried adding a dependency to `org.jetbrains.kotlinx:kotlinx-benchmark-runtime-jvm` but that did not help either.

**Comment by qurbonzoda** [comment]
Hi @deepak-nulu,
This is your script for declaring dependencies for the `benchmarks` source set.
```
sourceSets.getByName("benchmarks") {
     dependencies {
         implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime:$kotlinBenchmarkVersion")
         implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime-jvm:$kotlinBenchmarkVersion")

 //        implementation(sourceSets.main.get().output)
 //        implementation(sourceSets.main.get().runtimeClasspath)
     }
 }
```
The problem here is `sourceSets.getByName("benchmarks") { body }` passes an instance of `SourceSet` type as `this` into body.
`SourceSet` set does not have `dependencies` function, thus the invocation resolves to `Project.dependencies`.
You can observe the result by looking at dependencies of `compileClasspath` configuration.

To fix the problem please use `kotlin.sourceSets.getByName("benchmarks") { body }`, which passes `KotlinSourceSet` as the receiver. `dependencies` invocation now should be resolved to `KotlinSourceSet.dependencies`.

**Comment by qurbonzoda** [comment]
> I tried adding a dependency to org.jetbrains.kotlinx:kotlinx-benchmark-runtime-jvm but that did not help either.

`org.jetbrains.kotlinx:kotlinx-benchmark-runtime` should be enough

**Comment by deepak-nulu** [comment]
Thank you @qurbonzoda for your detailed explanation! Your suggestion worked! 🙏
